version: 2
jobs:
  build:
    working_directory: /temp
    docker:
      - image: microsoft/dotnet:latest
    environment:
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
    steps:
      - checkout
      - run: dotnet build hypepool.sln
      - run: cd src/Tests/Hypepool.Core.Tests/ && dotnet xunit
      - run: cd src/Tests/Hypepool.Common.Tests/ && dotnet xunit
      - run: cd src/Tests/Hypepool.Monero.Tests/ && dotnet xunit
      - run: cd src/Tests/Hypepool.Benchmarks/ && dotnet build --configuration Release && cd bin/Release/netcoreapp2.0/ &&  dotnet Hypepool.Benchmarks.dll