version: 2
jobs:
  build:
    working_directory: /temp
    docker:
      - image: microsoft/dotnet:latest
    environment:
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
    steps:
      - checkout
      - run: dotnet build hypepool.sln
      - run: cd src/Core/Hypepool.Tests/ && dotnet xunit
